version: '3.8'

services:
  npm: &npm
    image: node:16
    volumes:
      - ./:/devstronomy/ui
    entrypoint: npm
    working_dir: /devstronomy/ui

  install-dependencies:
    <<: *npm
    command: install

  dev-server:
    <<: *npm
    command: start
    stdin_open: true
    ports:
      - '8080:8080'
