#!/bin/bash

# Helper script for quick testing '@devstronomy/canvas' locally before publishing.

git_root_dir=`realpath "$(dirname "$0")/.."`
devstronomy_canvas_dir="$git_root_dir/../canvas"
version="0.4.0-alpha.1"

set -xeuo pipefail

cd "$devstronomy_canvas_dir"

npm run clean:dist
npm pack

cd "$git_root_dir"

rm -rf "$git_root_dir/node_modules/@devstronomy/canvas"
npm install -SE "$devstronomy_canvas_dir/devstronomy-canvas-$version.tgz"
