#!/bin/bash

# Helper script for quick testing '@devstronomy/canvas' locally before publishing.

root_dir=`realpath "$(dirname "$0")/.."`
devstronomy_canvas_dir="$root_dir/../canvas"
version="0.3.2-alpha.1"

set -xeuo pipefail

cd "$devstronomy_canvas_dir"

npm run clean:dist
npm pack

cd "$root_dir"

npm install -SE "$devstronomy_canvas_dir/devstronomy-canvas-$version.tgz"
