export const SET_PLANETS = 'SET_PLANETS'
export const LOAD_PLANETS = 'LOAD_PLANETS'
export const SELECT_PLANET = 'SELECT_PLANET'

export const LOAD_SATELLITES = 'LOAD_SATELLITES'
export const SET_SATELLITES = 'SET_SATELLITES'
